version: '3.8'

services:
  # خدمة قاعدة البيانات
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: timetable-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - timetable-network
    restart: always

  # خدمة الواجهة الخلفية
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: timetable-backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=TimetableDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
      - Jwt__Key=YourSuperSecretKey123!@#$%^&*()_+
      - Jwt__Issuer=https://timetable.example.com
      - Jwt__Audience=https://timetable.example.com
      - Jwt__ExpireDays=7
    ports:
      - "5000:80"
    depends_on:
      - db
    networks:
      - timetable-network
    restart: always

  # خدمة الواجهة الأمامية
  frontend:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
    container_name: timetable-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - timetable-network
    restart: always

networks:
  timetable-network:
    driver: bridge

volumes:
  sqlserver_data:
